/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEmpleado;
import Controlador.DAO.DAOEmpleados;
import Modelo.Empleado;
import java.sql.SQLException;
import javax.swing.ButtonGroup;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Carlos
 */
public class VtnAgrega_oModificaEmpleados extends javax.swing.JFrame {

    //creamos una instancia de esta clase.
    private static VtnAgrega_oModificaEmpleados instanciaVtnAgregaoModificaEmpleado
            = new VtnAgrega_oModificaEmpleados();

    /*Creamos la variable, que nos indica si la ventana servirá para
     modificar o agregar la información de un empleado, en falso:*/
    private boolean seModificaraEmpleado;
     private Empleado empleadoDeLaTabla;

    /**
     * Creates new form VtnAgrega_oModificaEmpleados
     */
    private VtnAgrega_oModificaEmpleados() {
        initComponents();

        //colocamos la ventana en el centro.
        setLocationRelativeTo(null);
        /*Inicializamos la variable, que nos indica si la ventana servirá para
         modificar o agregar la información de un empleado, en falso:*/
        seModificaraEmpleado = false;
    }

    /**
     * método que se utiliza para el patrón singleton.
     *
     * @return la instancia de esta clase.
     */
    public static VtnAgrega_oModificaEmpleados getInstanciaVtnAgregaoModificaEmpleado() {
        return instanciaVtnAgregaoModificaEmpleado;
    }

    public Empleado getEmpleaedoDeLaTabla() {
        return empleadoDeLaTabla;
    }
    
    public void setEmpleadoDeLaTabla(Empleado empleadoDeLaTabla) {
        this.empleadoDeLaTabla = empleadoDeLaTabla;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotones = new javax.swing.ButtonGroup();
        btnGuardarEmpleado = new javax.swing.JButton();
        btnRegresarVtnEmpleados = new javax.swing.JButton();
        txtNombreEmpleado = new javax.swing.JTextField();
        lbNombreEmpleado = new javax.swing.JLabel();
        lbCorreo = new javax.swing.JLabel();
        lbDireccion = new javax.swing.JLabel();
        lbTelefono = new javax.swing.JLabel();
        lbSueldo = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        txtCorreoEmpleado = new javax.swing.JTextField();
        txtDireccionEmpleado = new javax.swing.JTextField();
        txtTelefonoEmpleado = new javax.swing.JTextField();
        txtSueldoEmpleado = new javax.swing.JTextField();
        lbId = new javax.swing.JLabel();
        txtIdEmpleado = new javax.swing.JTextField();
        lbDesempeno = new javax.swing.JLabel();
        cbDesempenio1 = new javax.swing.JCheckBox();
        cbDesempenio2 = new javax.swing.JCheckBox();
        cbDesempenio3 = new javax.swing.JCheckBox();
        cbDesempenio4 = new javax.swing.JCheckBox();
        cbDesempenio5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Empleado");

        btnGuardarEmpleado.setText("Guardar");
        btnGuardarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarEmpleadoActionPerformed(evt);
            }
        });

        btnRegresarVtnEmpleados.setText("Regresar");
        btnRegresarVtnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnEmpleadosActionPerformed(evt);
            }
        });

        lbNombreEmpleado.setText("Nombre:");

        lbCorreo.setText("Correo:");

        lbDireccion.setText("Dirección:");

        lbTelefono.setText("Teléfono:");

        lbSueldo.setText("Sueldo:");

        lbNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbNombre.setText("Empleado");

        txtCorreoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoEmpleadoActionPerformed(evt);
            }
        });

        txtTelefonoEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoEmpleadoActionPerformed(evt);
            }
        });

        lbId.setText("Id:");

        txtIdEmpleado.setEnabled(false);
        txtIdEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdEmpleadoActionPerformed(evt);
            }
        });

        lbDesempeno.setText("Desempeño:");

        grupoBotones.add(cbDesempenio1);
        cbDesempenio1.setText("1");

        grupoBotones.add(cbDesempenio2);
        cbDesempenio2.setText("2");

        grupoBotones.add(cbDesempenio3);
        cbDesempenio3.setText("3");

        grupoBotones.add(cbDesempenio4);
        cbDesempenio4.setText("4");

        grupoBotones.add(cbDesempenio5);
        cbDesempenio5.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCorreo)
                    .addComponent(lbDireccion)
                    .addComponent(lbSueldo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbDesempeno)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtSueldoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDesempenio1)
                                .addGap(26, 26, 26)
                                .addComponent(cbDesempenio2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbDesempenio3)
                                .addGap(30, 30, 30)
                                .addComponent(cbDesempenio4)
                                .addGap(27, 27, 27)
                                .addComponent(cbDesempenio5)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuardarEmpleado)
                .addGap(33, 33, 33)
                .addComponent(btnRegresarVtnEmpleados)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombre)
                    .addComponent(lbId)
                    .addComponent(txtIdEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNombreEmpleado))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDireccion))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccionEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCorreo))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefonoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTelefono))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSueldoEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSueldo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDesempeno)
                    .addComponent(cbDesempenio1)
                    .addComponent(cbDesempenio2)
                    .addComponent(cbDesempenio3)
                    .addComponent(cbDesempenio4)
                    .addComponent(cbDesempenio5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarEmpleado)
                    .addComponent(btnRegresarVtnEmpleados))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCorreoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoEmpleadoActionPerformed

    private void btnRegresarVtnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnEmpleadosActionPerformed
        VtnEmpleados vtnRegreso = VtnEmpleados.getInstanciaDeVtnEmpleados();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();
    }//GEN-LAST:event_btnRegresarVtnEmpleadosActionPerformed

    private void txtTelefonoEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoEmpleadoActionPerformed

    private void btnGuardarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarEmpleadoActionPerformed
        //Primero obtenemos los datos del empleado
        //y las guardamos en las siguientes variables:

        int id;
        if (!this.txtIdEmpleado.getText().isEmpty()) {
            id = Integer.parseInt(this.txtIdEmpleado.getText());
        }else{
            id =0;
        }

        float desempenio = 0;

        if (this.cbDesempenio1.isSelected() == true) {
            desempenio = 1;
        }
        if (this.cbDesempenio2.isSelected() == true) {
            desempenio = 2;
        }
        if (this.cbDesempenio3.isSelected() == true) {
            desempenio = 3;
        }
        if (this.cbDesempenio4.isSelected() == true) {
            desempenio = 4;
        }
        if (this.cbDesempenio5.isSelected() == true) {
            desempenio = 5;
        }

        String nombre = this.txtNombreEmpleado.getText();
        String direccion = this.txtDireccionEmpleado.getText();
        String telefono = this.txtTelefonoEmpleado.getText();
        String correo = this.txtCorreoEmpleado.getText();
        float sueldo = Float.parseFloat(this.txtSueldoEmpleado.getText());

        //Creamos la variable temporal de empleado..
        Empleado empleadoTemporal = new Empleado(id, nombre, direccion,
                telefono, correo, desempenio, sueldo);

        //creamos su controlador:
        ControladorEmpleado ctrlEmpleado = new ControladorEmpleado();

        try {
            if (seModificaraEmpleado) {
                boolean seModificoEmpleado = ctrlEmpleado.modificar(empleadoTemporal);
                if (seModificoEmpleado) {
                    mostrarMensajeEnPantalla("Empleado Modificado");
                } else {
                    mostrarMensajeEnPantalla("Empleado No Modificado");
                }
                //lo devolvemos a su estado inicial.
                seModificaraEmpleado = false;
            } else {
                boolean seAgregoEmpleado = ctrlEmpleado.agregar(empleadoTemporal);
                if (seAgregoEmpleado) {
                    mostrarMensajeEnPantalla("Empleado Agregado");
                } else {
                    mostrarMensajeEnPantalla("Empleado No Agregado");
                }

            }
        } catch (SQLException ex) {
            mostrarMensajeEnPantalla("Hubo un error con la "
                    + "base de datos. " + ex.getLocalizedMessage());
        }
        //borramos los datos:
        borrarDatosDeCampos();


    }//GEN-LAST:event_btnGuardarEmpleadoActionPerformed

    private void txtIdEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdEmpleadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdEmpleadoActionPerformed

    /**
     * Este método sirve para mostrar un mensaje en la pantalla.
     *
     * @param mensaje, es el mensaje que se debe mostrar en la pantalla.
     */
    private void mostrarMensajeEnPantalla(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Cuidado", 1);
    }

    /**
     * Este método se encarga de dejar todo como estaba para poder cerrar la
     * ventana.
     */
    private void cerrarEstaVentana() {
        borrarDatosDeCampos();
        this.dispose();
    }

    /**
     * Este método se encarga de limpiar los campos de la ventana.
     */
    private void borrarDatosDeCampos() {
        this.txtNombreEmpleado.setText("");
        this.txtNombreEmpleado.requestFocus();
        this.txtIdEmpleado.setText("");
        this.txtDireccionEmpleado.setText("");
        this.txtTelefonoEmpleado.setText("");
        this.txtCorreoEmpleado.setText("");
        this.txtSueldoEmpleado.setText("");
        this.grupoBotones.clearSelection();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgrega_oModificaEmpleados().setVisible(true);
            }
        });
    }

    /**
     * @return the txtCorreoEmpleado
     */
    public javax.swing.JTextField getTxtCorreoEmpleado() {
        return txtCorreoEmpleado;
    }

    /**
     * @return the txtDireccionEmpleado
     */
    public javax.swing.JTextField getTxtDireccionEmpleado() {
        return txtDireccionEmpleado;
    }

    /**
     * @return the txtNombreEmpleado
     */
    public javax.swing.JTextField getTxtNombreEmpleado() {
        return txtNombreEmpleado;
    }

    public ButtonGroup getGrupoBotones() {
        return grupoBotones;
    }

    public double getValCbDesempenio1() {
        return 1.0;
    }

    public double getValCbDesempenio2() {
        return 2.0;
    }

    public double getValCbDesempenio3() {
        return 3.0;
    }

    public double getValCbDesempenio4() {
        return 4.0;
    }

    public double getValCbDesempenio5() {
        return 5.0;
    }

    public JCheckBox getCbDesempenio1() {
        return cbDesempenio1;
    }

    public JCheckBox getCbDesempenio2() {
        return cbDesempenio2;
    }

    public JCheckBox getCbDesempenio3() {
        return cbDesempenio3;
    }

    public JCheckBox getCbDesempenio4() {
        return cbDesempenio4;
    }

    
    public JCheckBox getCbDesempenio5() {
        return cbDesempenio5;
    }

    
    /**
     * @return the txtTelefonoEmpleado
     */
    public javax.swing.JTextField getTxtTelefonoEmpleado() {
        return txtTelefonoEmpleado;
    }

    public javax.swing.JTextField getTxtSueldoEmpleado() {
        return txtSueldoEmpleado;
    }

    /**
     * @return the seModificaraEmpleado, que es la variable que indica si esta
     * ventana se usará para modificar o agregar la información de un empleado a
     * la base de datos.
     */
    public boolean isSeModificaraEmpleado() {
        return seModificaraEmpleado;
    }

    /**
     * @param seModificaraEmpleado Establece la variable que indica si esta
     * ventana se usará para modificar un empleado, en cuyo caso debería ponerse
     * en true, si no, se usará para agregar un empleado, cuyo caso se pondría
     * en false.
     */
    public void setSeModificaraEmpleado(boolean seModificaraEmpleado) {
        this.seModificaraEmpleado = seModificaraEmpleado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarEmpleado;
    private javax.swing.JButton btnRegresarVtnEmpleados;
    private javax.swing.JCheckBox cbDesempenio1;
    private javax.swing.JCheckBox cbDesempenio2;
    private javax.swing.JCheckBox cbDesempenio3;
    private javax.swing.JCheckBox cbDesempenio4;
    private javax.swing.JCheckBox cbDesempenio5;
    private javax.swing.ButtonGroup grupoBotones;
    private javax.swing.JLabel lbCorreo;
    private javax.swing.JLabel lbDesempeno;
    private javax.swing.JLabel lbDireccion;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNombreEmpleado;
    private javax.swing.JLabel lbSueldo;
    private javax.swing.JLabel lbTelefono;
    private javax.swing.JTextField txtCorreoEmpleado;
    private javax.swing.JTextField txtDireccionEmpleado;
    private javax.swing.JTextField txtIdEmpleado;
    private javax.swing.JTextField txtNombreEmpleado;
    private javax.swing.JTextField txtSueldoEmpleado;
    private javax.swing.JTextField txtTelefonoEmpleado;
    // End of variables declaration//GEN-END:variables

    public JTextField getTxtIdEmpleado() {
        return txtIdEmpleado;
    }

}
