/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorMesaDeDulces;
import Controlador.DAO.DAOMesaDeDulces;
import Modelo.MesaDeDulces;
import java.sql.SQLException;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Alejandro
 */
public class VtnAgrega_oModificaMesaDeDulces extends javax.swing.JFrame {

    private static VtnAgrega_oModificaMesaDeDulces instanciaVtnAgregaoModificaMesaDeDulces = new VtnAgrega_oModificaMesaDeDulces();
    private boolean seModificaraMesaDeDulces;
    private MesaDeDulces mesaDeDulcesDeLaTabla;

    /**
     * Creates new form VtnAgrega_oModificaMesaDeDulces
     */
    public VtnAgrega_oModificaMesaDeDulces() {
        initComponents();
        setLocationRelativeTo(null);
        seModificaraMesaDeDulces = false;
    }
    
    public static VtnAgrega_oModificaMesaDeDulces getInstanciaVtnAgrega_oModificaMesaDeDulces() {
        return instanciaVtnAgregaoModificaMesaDeDulces;
    }

    public JTextField getTxtIdMesaDeDulces() {
        return txtIdMesaDeDulces;
    }

    public void setTxtIdMesaDeDulces(JTextField txtIdMesaDeDulces) {
        this.txtIdMesaDeDulces = txtIdMesaDeDulces;
    }

    public JTextField getTxtNombreMesaDeDulces() {
        return txtNombreMesaDeDulces;
    }

    public void setTxtNombreMesaDeDulces(JTextField txtNombreMesaDeDulces) {
        this.txtNombreMesaDeDulces = txtNombreMesaDeDulces;
    }

    public JTextField getTxtPrecioMesaDeDulces() {
        return txtPrecioMesaDeDulces;
    }

    public void setTxtPrecioMesaDeDulces(JTextField txtPrecioMesaDeDulces) {
        this.txtPrecioMesaDeDulces = txtPrecioMesaDeDulces;
    }

    public boolean isSeModificaraMesaDeDulces() {
        return seModificaraMesaDeDulces;
    }

    public void setSeModificaraMesaDeDulces(boolean seModificaraMesaDeDulces) {
        this.seModificaraMesaDeDulces = seModificaraMesaDeDulces;
    }

    public MesaDeDulces getMesaDeDulcesDeLaTabla() {
        return mesaDeDulcesDeLaTabla;
    }

    public void setMesaDeDulcesDeLaTabla(MesaDeDulces mesaDeDulcesDeLaTabla) {
        this.mesaDeDulcesDeLaTabla = mesaDeDulcesDeLaTabla;
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTitulo = new javax.swing.JLabel();
        txtNombreMesaDeDulces = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioMesaDeDulces = new javax.swing.JTextField();
        btnGuardarMesaDeDulces = new javax.swing.JButton();
        btnRegresarVtnMesaDeDulces = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtIdMesaDeDulces = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Mesa de Dulces");

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbTitulo.setText("Mesa de Dulces");

        txtNombreMesaDeDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreMesaDeDulcesActionPerformed(evt);
            }
        });

        jLabel2.setText("Nombre:");

        jLabel3.setText("Precio:");

        btnGuardarMesaDeDulces.setText("Guardar");
        btnGuardarMesaDeDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarMesaDeDulcesActionPerformed(evt);
            }
        });

        btnRegresarVtnMesaDeDulces.setText("Regresar");
        btnRegresarVtnMesaDeDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnMesaDeDulcesActionPerformed(evt);
            }
        });

        jLabel4.setText("Id:");

        txtIdMesaDeDulces.setEnabled(false);
        txtIdMesaDeDulces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdMesaDeDulcesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnGuardarMesaDeDulces)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarVtnMesaDeDulces))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdMesaDeDulces, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreMesaDeDulces, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioMesaDeDulces, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(jLabel4)
                    .addComponent(txtIdMesaDeDulces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreMesaDeDulces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecioMesaDeDulces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarMesaDeDulces)
                    .addComponent(btnRegresarVtnMesaDeDulces))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarVtnMesaDeDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnMesaDeDulcesActionPerformed
        // TODO add your handling code here:
        VtnMesaDeDulces vtnRegreso = VtnMesaDeDulces.getInstanciaDeVtnMesaDeDulces();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();
    }//GEN-LAST:event_btnRegresarVtnMesaDeDulcesActionPerformed

    private void mensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Cuidado", 1);
    }
    private void btnGuardarMesaDeDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarMesaDeDulcesActionPerformed
        // TODO add your handling code here:
        //Primero obtenemos los datos de la mesa de dulces
        //y las guardamos en las siguientes variables:
        //Primero obtenemos los datos de la mesa de dulces
        //y las guardamos en las siguientes variables:
        int id;
        if (!this.txtIdMesaDeDulces.getText().isEmpty()) {
            id = Integer.parseInt(this.txtIdMesaDeDulces.getText());
            
        }else{
            
            id = 0;
        }
        
        String nombre = this.txtNombreMesaDeDulces.getText();
        float precio = Float.parseFloat(this.txtPrecioMesaDeDulces.getText());

                
        //Creamos la variable temporal de cliente..
        MesaDeDulces tempMesaDeDulces = new MesaDeDulces(id, nombre, precio);
        ControladorMesaDeDulces ctrlMesaDeDulces = new ControladorMesaDeDulces();
        
        try {
            if (!seModificaraMesaDeDulces) {
                boolean seAgregoMesaDeDulces = ctrlMesaDeDulces.agregarMD(tempMesaDeDulces);
                 if (seAgregoMesaDeDulces) mensaje("Mesa de Dulces Agregada");
                 else mensaje("Mesa de Dulces No Agregada");
                
            }else{
                boolean seModificoMesaDeDulces = ctrlMesaDeDulces.modificarMD(tempMesaDeDulces);
                 if (seModificoMesaDeDulces) mensaje("Mesa de Dulces Modificada");
                 else  mensaje("Mesa de Dulces No Modificado");
                 //lo devolvemos a su estado de inicio.
                seModificaraMesaDeDulces = false;
            }
        } catch (SQLException ex) {
            mensaje("Hubo un error con la "
                    + "base de datos. " + ex.getLocalizedMessage());
        }

        borrarDatosDeCampos();

    }//GEN-LAST:event_btnGuardarMesaDeDulcesActionPerformed

    private void txtNombreMesaDeDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreMesaDeDulcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreMesaDeDulcesActionPerformed

    private void txtIdMesaDeDulcesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdMesaDeDulcesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdMesaDeDulcesActionPerformed

    private void borrarDatosDeCampos() {
        this.txtNombreMesaDeDulces.setText("");
        this.txtPrecioMesaDeDulces.setText("");
        this.txtIdMesaDeDulces.setText("");
        
    }

    private void cerrarEstaVentana() {
        borrarDatosDeCampos();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaMesaDeDulces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnAgrega_oModificaMesaDeDulces().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarMesaDeDulces;
    private javax.swing.JButton btnRegresarVtnMesaDeDulces;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JTextField txtIdMesaDeDulces;
    private javax.swing.JTextField txtNombreMesaDeDulces;
    private javax.swing.JTextField txtPrecioMesaDeDulces;
    // End of variables declaration//GEN-END:variables
}
