/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorProveedores;
import Modelo.Proveedor;
import Modelo.Servicio;
import java.sql.SQLException;
import java.util.LinkedList;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class VtnAgrega_oModificaProveedor extends javax.swing.JFrame {

    private static VtnAgrega_oModificaProveedor instanciaVtnAgregaoModificaProveedor
            = new VtnAgrega_oModificaProveedor();

    private boolean seModificaraProveedor;

    /**
     * Creates new form VtnAgrega_oModificaProveedor
     */
    private VtnAgrega_oModificaProveedor() {
        initComponents();
        //colocamos la ventana en el centro.
        setLocationRelativeTo(null);
        seModificaraProveedor = false;
        inicializarCamposDeEvento();
    }

    public static VtnAgrega_oModificaProveedor getInstanciaVtnAgregaoModificaProveedor() {
        return instanciaVtnAgregaoModificaProveedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarProveedor = new javax.swing.JButton();
        txtDireccionProveedor = new javax.swing.JTextField();
        txtCorreoProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        txtNombreProveedor = new javax.swing.JTextField();
        btnRegresarVtnProveedores = new javax.swing.JButton();
        Correo = new javax.swing.JLabel();
        Dirección = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tituloProveedor = new javax.swing.JLabel();
        cbCarpaEvento = new javax.swing.JCheckBox();
        cbBanqueteraEvento = new javax.swing.JCheckBox();
        cbLucesEvento = new javax.swing.JCheckBox();
        cbLugarEvento = new javax.swing.JCheckBox();
        cbMusicaEvento = new javax.swing.JCheckBox();
        txtBanqueteraEvento = new javax.swing.JTextField();
        txtCarpaEvento = new javax.swing.JTextField();
        txtIluminacionEvento = new javax.swing.JTextField();
        txtLugarEvento = new javax.swing.JTextField();
        txtMusicaEvento = new javax.swing.JTextField();
        lblSeleccionar = new javax.swing.JLabel();
        lbId = new javax.swing.JLabel();
        lbPrecio = new javax.swing.JLabel();
        idBanquetera = new javax.swing.JLabel();
        idCarpa = new javax.swing.JLabel();
        idIluminacion = new javax.swing.JLabel();
        idLugar = new javax.swing.JLabel();
        idMusica = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Proveedor");

        btnGuardarProveedor.setText("Guardar");
        btnGuardarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProveedorActionPerformed(evt);
            }
        });

        txtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProveedorActionPerformed(evt);
            }
        });

        btnRegresarVtnProveedores.setText("Regresar");
        btnRegresarVtnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnProveedoresActionPerformed(evt);
            }
        });

        Correo.setText("Correo:");

        Dirección.setText("Dirección:");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Teléfono:");

        tituloProveedor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tituloProveedor.setText("Proveedor");

        cbCarpaEvento.setText("Carpa");
        cbCarpaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarpaEventoActionPerformed(evt);
            }
        });

        cbBanqueteraEvento.setText("Banquetera");
        cbBanqueteraEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbBanqueteraEventoActionPerformed(evt);
            }
        });

        cbLucesEvento.setText("Iluminación");
        cbLucesEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLucesEventoActionPerformed(evt);
            }
        });

        cbLugarEvento.setText("Lugar");
        cbLugarEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLugarEventoActionPerformed(evt);
            }
        });

        cbMusicaEvento.setText("Música");
        cbMusicaEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMusicaEventoActionPerformed(evt);
            }
        });

        txtBanqueteraEvento.setEditable(false);

        txtCarpaEvento.setEditable(false);

        txtIluminacionEvento.setEditable(false);

        txtLugarEvento.setEditable(false);

        txtMusicaEvento.setEditable(false);

        lblSeleccionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSeleccionar.setText("Seleccione los servicios del proveedor y establezca sus costos:");

        lbPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrecio.setText("Precio.");

        idBanquetera.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idBanquetera.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idBanquetera.setText("1");
        idBanquetera.setEnabled(false);

        idCarpa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idCarpa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idCarpa.setText("2");

        idIluminacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idIluminacion.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idIluminacion.setText("3");

        idLugar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idLugar.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idLugar.setText("4");

        idMusica.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idMusica.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        idMusica.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(161, 161, 161)
                                .addComponent(tituloProveedor))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1))
                            .addComponent(Correo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbId, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnRegresarVtnProveedores))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(247, 247, 247)
                                .addComponent(lbPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnGuardarProveedor)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(Dirección))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                        .addComponent(txtDireccionProveedor)
                                        .addComponent(txtNombreProveedor)
                                        .addComponent(txtCorreoProveedor))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(idCarpa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbCarpaEvento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(idMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(idLugar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(cbLugarEvento)
                                                    .addComponent(cbMusicaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(idIluminacion, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(cbLucesEvento))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(idBanquetera, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbBanqueteraEvento)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBanqueteraEvento)
                                    .addComponent(txtLugarEvento)
                                    .addComponent(txtIluminacionEvento)
                                    .addComponent(txtMusicaEvento, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCarpaEvento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tituloProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTelefonoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Dirección)
                    .addComponent(txtDireccionProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Correo)
                    .addComponent(txtCorreoProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbPrecio)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idBanquetera, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbBanqueteraEvento)
                    .addComponent(txtBanqueteraEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCarpaEvento)
                    .addComponent(idCarpa)
                    .addComponent(txtCarpaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIluminacionEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLucesEvento)
                    .addComponent(idIluminacion))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLugarEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbLugarEvento)
                    .addComponent(idLugar))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMusicaEvento)
                    .addComponent(idMusica)
                    .addComponent(txtMusicaEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProveedor)
                    .addComponent(btnRegresarVtnProveedores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProveedorActionPerformed

    private void cbCarpaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarpaEventoActionPerformed
        if (this.cbCarpaEvento.isSelected()) {
            this.txtCarpaEvento.setEditable(true);
        }
    }//GEN-LAST:event_cbCarpaEventoActionPerformed

    private void cbMusicaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMusicaEventoActionPerformed
        if (this.cbMusicaEvento.isSelected()) {
            this.txtMusicaEvento.setEditable(true);
        }
    }//GEN-LAST:event_cbMusicaEventoActionPerformed

    private void txtBanqueteraEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBanqueteraEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBanqueteraEventoActionPerformed

    private void cbBanqueteraEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbBanqueteraEventoActionPerformed
        if (this.cbBanqueteraEvento.isSelected()) {
            this.txtBanqueteraEvento.setEditable(true);
        }
    }//GEN-LAST:event_cbBanqueteraEventoActionPerformed

    private void txtLucesEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLucesEventoActionPerformed

    }//GEN-LAST:event_txtLucesEventoActionPerformed

    private void txtLugarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLugarEventoActionPerformed

    }//GEN-LAST:event_txtLugarEventoActionPerformed

    private void txtMusicaEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMusicaEventoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMusicaEventoActionPerformed

    private void inicializarCamposDeEvento() {
        this.txtBanqueteraEvento.setEditable(false);
        this.txtCarpaEvento.setEditable(false);
        this.txtIluminacionEvento.setEditable(false);
        this.txtMusicaEvento.setEditable(false);
        this.txtLugarEvento.setEditable(false);
    }


    private void btnGuardarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProveedorActionPerformed

        LinkedList<Servicio> servicios = obtenerServicioSeleccionados();

        String nombre = this.txtNombreProveedor.getText();
        String direccion = this.txtDireccionProveedor.getText();
        String telefono = this.txtTelefonoProveedor.getText();
        String correo = this.txtCorreoProveedor.getText();

        Proveedor tempProveedor = new Proveedor(0, nombre, direccion, telefono, correo);
        tempProveedor.setServiciosQueProvee(servicios);

        ControladorProveedores ctrlProveedor = new ControladorProveedores();

        try {

            if (!seModificaraProveedor) {
                boolean seAgregoProveedor = ctrlProveedor.agregar(tempProveedor);
                if (seAgregoProveedor) {
                    mostrarMensajeEnPantalla("Proveedor Agregado");
                } else {
                    mostrarMensajeEnPantalla("Proveedor No Agregado");
                }

            } else {
                /*
                 El label del id, tiene el id del proveedor 
                 en formato de String; entonces:
                 */
                int id = Integer.parseInt(this.lbId.getText());
                tempProveedor.setIdPersona(id);
                boolean seModificoProveedor = ctrlProveedor.modificar(tempProveedor);
                if (seModificoProveedor) {
                    mostrarMensajeEnPantalla("Proveedor Modificado");
                } else {
                    mostrarMensajeEnPantalla("Proveedor No Modificado");
                }
                //lo devolvemos a su estado de inicio.
                seModificaraProveedor = false;

            }
        } catch (SQLException ex) {
            mostrarMensajeEnPantalla("Hubo un error con la "
                    + "base de datos. *******Fue en agregar Proveedor*****" + ex.getLocalizedMessage());

        }
    }//GEN-LAST:event_btnGuardarProveedorActionPerformed

    private LinkedList<Servicio> obtenerServicioSeleccionados() {
        LinkedList<Servicio> servicios = new LinkedList<>();

        float precioServicio = 0;
        int idServicio = 0;
        if (this.cbBanqueteraEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtBanqueteraEvento.getText());
            idServicio = Integer.parseInt(this.idBanquetera.getText());

            servicios.add(new Servicio(idServicio, "Banquetera", precioServicio));
        }
        if (this.cbCarpaEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtCarpaEvento.getText());
            idServicio = Integer.parseInt(this.idCarpa.getText());

            servicios.add(new Servicio(idServicio, "Carpa", precioServicio));

        }
        if (this.cbLucesEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtIluminacionEvento.getText());
            idServicio = Integer.parseInt(this.idIluminacion.getText());

            servicios.add(new Servicio(idServicio, "Iluminacion", precioServicio));

        }
        if (this.cbLugarEvento.isSelected()) {

            precioServicio = Float.parseFloat(this.txtLugarEvento.getText());
            idServicio = Integer.parseInt(this.idLugar.getText());

            servicios.add(new Servicio(idServicio, "Lugar", precioServicio));

        }
        if (this.cbMusicaEvento.isSelected()) {
            precioServicio = Float.parseFloat(this.txtMusicaEvento.getText());
            idServicio = Integer.parseInt(this.idMusica.getText());

            servicios.add(new Servicio(idServicio, "Musica", precioServicio));
        }
        return servicios;
    }


    private void btnRegresarVtnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnProveedoresActionPerformed
        VtnProveedores vtnRegreso = VtnProveedores.getInstanciaDeVtnProveedores();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();

    }//GEN-LAST:event_btnRegresarVtnProveedoresActionPerformed

    private void cbLucesEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLucesEventoActionPerformed
        if (this.cbLucesEvento.isSelected()) {
            this.txtIluminacionEvento.setEditable(true);
        } else {
            this.txtIluminacionEvento.setText("");
            this.txtIluminacionEvento.setEditable(false);
        }
    }//GEN-LAST:event_cbLucesEventoActionPerformed

    private void cbLugarEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLugarEventoActionPerformed
        if (this.cbLugarEvento.isSelected()) {
            this.txtLugarEvento.setEditable(true);
        } else {
            this.txtLugarEvento.setText("");
            this.txtLugarEvento.setEditable(false);
        }
    }//GEN-LAST:event_cbLugarEventoActionPerformed

    private void mostrarMensajeEnPantalla(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje, "Cuidado", 1);
    }

    private void borraDatosDeCampos() {
        this.txtCorreoProveedor.setText("");
        this.txtDireccionProveedor.setText("");
        this.txtNombreProveedor.setText("");
        this.txtTelefonoProveedor.setText("");
        this.txtBanqueteraEvento.setText("");
        this.txtCarpaEvento.setText("");
        this.txtIluminacionEvento.setText("");
        this.txtLugarEvento.setText("");
        this.txtMusicaEvento.setText("");
        this.cbBanqueteraEvento.setSelected(false);
        this.cbCarpaEvento.setSelected(false);
        this.cbLucesEvento.setSelected(false);
        this.cbLugarEvento.setSelected(false);
        this.cbMusicaEvento.setSelected(false);
    }

    private void cerrarEstaVentana() {
        borraDatosDeCampos();
        this.dispose();
    }

    public javax.swing.JTextField getTxtCorreoProveedor() {
        return txtCorreoProveedor;
    }

    /**
     * @return the txtDireccionCliente
     */
    public javax.swing.JTextField getTxtDireccionProveedor() {
        return txtDireccionProveedor;
    }

    /**
     * @return the txtNombreCliente
     */
    public javax.swing.JTextField getTxtNombreProveedor() {
        return txtNombreProveedor;
    }

    /**
     * @return the txtTelefonoCliente
     */
    public javax.swing.JTextField getTxtTelefonoProveedor() {
        return txtTelefonoProveedor;
    }

    public javax.swing.JTextField getTxtBanqueterEvento() {
        return txtBanqueteraEvento;
    }

    public javax.swing.JTextField getTxtCarpaEvento() {
        return txtCarpaEvento;
    }

    public javax.swing.JTextField getTxtLucesEvento() {
        return txtIluminacionEvento;
    }

    public javax.swing.JTextField getTxtLugarEvento() {
        return txtLugarEvento;
    }

    public javax.swing.JTextField getTxtMusicaEvento() {
        return txtMusicaEvento;
    }

    public JCheckBox getCbCarpaEvento() {
        return cbCarpaEvento;
    }

    public JCheckBox getCbLucesEvento() {
        return cbLucesEvento;
    }

    public JCheckBox getCbBanqueteraEvento() {
        return cbBanqueteraEvento;
    }

    public JCheckBox getCbLugarEvento() {
        return cbLugarEvento;
    }

    public JCheckBox getCbMusicaEvento() {
        return cbMusicaEvento;
    }

    /**
     * @return the seModificaraCliente
     */
    public boolean isSeModificaraProveedor() {
        return seModificaraProveedor;
    }

    /**
     * @param seModificaraProveedor
     */
    public void setSeModificaraProveedor(boolean seModificaraProveedor) {
        this.seModificaraProveedor = seModificaraProveedor;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnAgrega_oModificaProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new VtnAgrega_oModificaProveedor().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Correo;
    private javax.swing.JLabel Dirección;
    private javax.swing.JButton btnGuardarProveedor;
    private javax.swing.JButton btnRegresarVtnProveedores;
    private javax.swing.JCheckBox cbBanqueteraEvento;
    private javax.swing.JCheckBox cbCarpaEvento;
    private javax.swing.JCheckBox cbLucesEvento;
    private javax.swing.JCheckBox cbLugarEvento;
    private javax.swing.JCheckBox cbMusicaEvento;
    private javax.swing.JLabel idBanquetera;
    private javax.swing.JLabel idCarpa;
    private javax.swing.JLabel idIluminacion;
    private javax.swing.JLabel idLugar;
    private javax.swing.JLabel idMusica;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbPrecio;
    private javax.swing.JLabel lblSeleccionar;
    private javax.swing.JLabel tituloProveedor;
    private javax.swing.JTextField txtBanqueteraEvento;
    private javax.swing.JTextField txtCarpaEvento;
    private javax.swing.JTextField txtCorreoProveedor;
    private javax.swing.JTextField txtDireccionProveedor;
    private javax.swing.JTextField txtIluminacionEvento;
    private javax.swing.JTextField txtLugarEvento;
    private javax.swing.JTextField txtMusicaEvento;
    private javax.swing.JTextField txtNombreProveedor;
    private javax.swing.JTextField txtTelefonoProveedor;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lbId
     */
    public javax.swing.JLabel getLbId() {
        return lbId;
    }
}
