/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEventos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import Controlador.ControladorReporGanancias;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Calendar;
import java.util.Date;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;

/**
 *
 * @author Carlos
 */
public class VtnReporGanancias extends javax.swing.JFrame {

    //private static VtnReporGanancias instanciaDeVtnReporGanancias = new VtnReporGanancias();
    private int tipoDellenado = 0;

    /**
     * Creates new form VtnReporGanancias
     */
    public VtnReporGanancias() {

        initComponents();
        setLocationRelativeTo(null);
        limpiarTabla();
        mostrarEventos();
        establecerMontoTotal();
        EstablecerMesConMasVentas();
        EstablecerMesConMenosVentas();
    }

  
    private void mostrarEventos() {
        ControladorEventos ctrlEventos = new ControladorEventos();
        try {
            DefaultTableModel datosTabla = (DefaultTableModel) this.reporteTablaGanancias.getModel();
            DefaultTableModel datosTablaCompleta = ctrlEventos.obtenerTodosLosEventos(datosTabla, tipoDellenado);

            //System.out.println("datos" +datosTablaCompleta.getValueAt(1,3));
            this.reporteTablaGanancias.setModel(datosTablaCompleta);

        } catch (SQLException ex) {
            Logger.getLogger(VtnEventosSociales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void EstablecerMesConMasVentas() {

        String mesConMasVentas = "";
        DefaultTableModel modelo = (DefaultTableModel) this.reporteTablaGanancias.getModel();
        ControladorReporGanancias ctrlReporGanancias = new ControladorReporGanancias();
        mesConMasVentas = ctrlReporGanancias.CalcularMesConMasVentas(modelo);

        this.mejorMes.setText(mesConMasVentas);
    }

    private void EstablecerMesConMenosVentas() {

        String mesConMenosVentas = "";
        DefaultTableModel modelo = (DefaultTableModel) this.reporteTablaGanancias.getModel();
        ControladorReporGanancias ctrlReporGanancias = new ControladorReporGanancias();
        mesConMenosVentas = ctrlReporGanancias.CalcularMesConMenosVentas(modelo);

        this.peorMes.setText(mesConMenosVentas);
    }

    private void establecerMontoTotal() {
        float montoTotal = 0;
        DefaultTableModel modelo = (DefaultTableModel) this.reporteTablaGanancias.getModel();
        ControladorReporGanancias ctrlReporGanancias = new ControladorReporGanancias();
        montoTotal = ctrlReporGanancias.calcularMontoTotal(modelo);

        this.montoTotal.setText(String.valueOf(montoTotal));
    }

    public void limpiarTabla() {
        DefaultTableModel modeloDeLaTabla = (DefaultTableModel) this.reporteTablaGanancias.getModel();
        for (int i = 0; i < reporteTablaGanancias.getRowCount(); i++) {
            modeloDeLaTabla.removeRow(0);
            i -= 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        reporteTablaGanancias = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnRegresarVtnReportes = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        montoTotal = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        mejorMes = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        peorMes = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Reporte Ganancias");

        reporteTablaGanancias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Evento", "Fecha", "Precio"
            }
        ));
        jScrollPane1.setViewportView(reporteTablaGanancias);

        jButton1.setText("Generar Reporte Mensual");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnRegresarVtnReportes.setText("Regresar");
        btnRegresarVtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnReportesActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Reportes de las Ganancias");

        jLabel2.setText("Monto Total:");

        montoTotal.setEditable(false);
        montoTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoTotalActionPerformed(evt);
            }
        });

        jButton2.setText("Generar Reporte Hasta el Momento");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Mejor Mes:");

        mejorMes.setEditable(false);

        jLabel4.setText("Peor Mes:");

        peorMes.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRegresarVtnReportes))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mejorMes)
                                    .addComponent(peorMes))
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(montoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(montoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(mejorMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(peorMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegresarVtnReportes)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarVtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnReportesActionPerformed
        VtnReportes vtnRegreso = VtnReportes.getInstanciaDeVtnReportes();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarVtnReportesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void montoTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoTotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        FileOutputStream out = null;
        Calendar calendario = Calendar.getInstance();
        try {
            // TODO add your handling code here:
            
            Workbook wb = new HSSFWorkbook();
            CreationHelper createhelper = wb.getCreationHelper();
            Sheet sheet = wb.createSheet("Reporte Hasta Este Momento");
            Row row = null;
            Cell cell = null;
            TableModel tableModel = this.reporteTablaGanancias.getModel();

            crearEncabezados(sheet, tableModel);
            poblarExcel(sheet, tableModel);

            out = new FileOutputStream("reporteGanancias.xls");
            wb.write(out);
            out.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VtnReporEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VtnReporEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

        private void poblarExcel(Sheet sheet, TableModel tableModel) {
        Row row;
        Cell cell;
        for (int i = 1; i < tableModel.getRowCount()+4; i++) {
                row = sheet.createRow(i);
                for (int j = 0; j <  tableModel.getColumnCount(); j++) {
                    cell =  row.createCell(j);
                    String dinero = (j>1)? "$":"";
                    cell.setCellValue(dinero + String.valueOf(tableModel.getValueAt(i-1, j)));
                }
            }
        
    }
    private void crearEncabezados(Sheet sheet, TableModel tableModel) {
        Row row = sheet.createRow(0);
        Cell cell = null;
        for (int i = 0; i < tableModel.getColumnCount(); i++) {
            cell = row.createCell(i);
            cell.setCellValue(tableModel.getColumnName(i));
        }
    }

    private void cerrarEstaVentana() {
        //BorrarDatos();
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnReporGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnReporGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnReporGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnReporGanancias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnReporGanancias().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresarVtnReportes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mejorMes;
    private javax.swing.JTextField montoTotal;
    private javax.swing.JTextField peorMes;
    private javax.swing.JTable reporteTablaGanancias;
    // End of variables declaration//GEN-END:variables
}
