/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControladorEmpleado;
import java.io.FileNotFoundException;

import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CreationHelper;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;
/**
 *
 * @author Carlos
 */
public class VtnReporEmpleados extends javax.swing.JFrame {

    private static VtnReporEmpleados instanciaDeVtnReporEmpleados = new VtnReporEmpleados();

    /**
     * Creates new form VtnReporEmpleados
     */
    public VtnReporEmpleados() {
        initComponents();
        setLocationRelativeTo(null);
        listarEmpleados();
    }

    public static VtnReporEmpleados getInstanciaDeVtnReporEmpleados() {
        return instanciaDeVtnReporEmpleados;
    }

    private void cerrarEstaVentana() {
        //borrarDatos();
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnExportarExcel = new javax.swing.JButton();
        btnRegresarVtnReportes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reporteTablaEmpleados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Reporte Empleados");

        btnExportarExcel.setText("Exportar a Excel");
        btnExportarExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarExcelActionPerformed(evt);
            }
        });

        btnRegresarVtnReportes.setText("Regresar");
        btnRegresarVtnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVtnReportesActionPerformed(evt);
            }
        });

        reporteTablaEmpleados.setAutoCreateRowSorter(true);
        reporteTablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Ordenar x Desempeño", "Ordernar x Sueldo", "Ordernar x Total Vendido"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(reporteTablaEmpleados);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Reportes de los Empleados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnExportarExcel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarVtnReportes))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 388, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExportarExcel)
                    .addComponent(btnRegresarVtnReportes))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarVtnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVtnReportesActionPerformed
        VtnReportes vtnRegreso = VtnReportes.getInstanciaDeVtnReportes();
        vtnRegreso.setVisible(true);
        cerrarEstaVentana();

        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarVtnReportesActionPerformed

    private void btnExportarExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarExcelActionPerformed
        FileOutputStream out = null;
        try {
            // TODO add your handling code here:
            Workbook wb = new HSSFWorkbook();
            CreationHelper createhelper = wb.getCreationHelper();
            Sheet sheet = wb.createSheet("new sheet");
            Row row = null;
            Cell cell = null;
            TableModel tableModel = this.reporteTablaEmpleados.getModel();
            
            crearEncabezados(sheet,tableModel);
            poblarExcel(sheet, tableModel);
              
            out = new FileOutputStream("reporteEmpleados.xls");
            wb.write(out);
            out.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VtnReporEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(VtnReporEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnExportarExcelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VtnReporEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VtnReporEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VtnReporEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VtnReporEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VtnReporEmpleados().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportarExcel;
    private javax.swing.JButton btnRegresarVtnReportes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable reporteTablaEmpleados;
    // End of variables declaration//GEN-END:variables

    private void listarEmpleados() {
        ControladorEmpleado unControlador = new ControladorEmpleado();

        try {
            LinkedList listaDeEmpleados = unControlador.buscarTodosLosEmpleadosConVentas();

            Object columnasDeDatos[] = new Object[4];

            //obtenemos el modelo default de la tabla:
            DefaultTableModel modeloDeLaTabla = (DefaultTableModel) this.reporteTablaEmpleados.getModel();
            limpiarTabla();
            if (listaDeEmpleados != null) {
                //agregamos a cada columna los datos que le corresponden:
                for (int dato = 0; dato < listaDeEmpleados.size(); dato = dato + 4) {
                    columnasDeDatos[0] = listaDeEmpleados.get(dato);
                    columnasDeDatos[1] = listaDeEmpleados.get(dato + 1);
                    columnasDeDatos[2] = listaDeEmpleados.get(dato + 2);
                    columnasDeDatos[3] = listaDeEmpleados.get(dato + 3);

                    //agregamos los datos de cada columna en cada renglón:
                    modeloDeLaTabla.addRow(columnasDeDatos);

                }
            } else {
                /*El else no es necesario, pero fue considerado.*/
            }
            //establecemos a nuestra tabla, el modelo que tenía:
            this.reporteTablaEmpleados.setModel(modeloDeLaTabla);

        } catch (SQLException ex) {
            Logger.getLogger(VtnReporEmpleados.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void limpiarTabla() {
        DefaultTableModel modeloDeLaTabla = (DefaultTableModel) this.reporteTablaEmpleados.getModel();
        for (int i = 0; i < reporteTablaEmpleados.getRowCount(); i++) {
            modeloDeLaTabla.removeRow(0);
            i -= 1;
        }
    }

    private void crearEncabezados(Sheet sheet, TableModel tableModel) {
        Row row = sheet.createRow(0);
        Cell cell = null;
            for (int i = 0; i < tableModel.getColumnCount(); i++) {
                cell =  row.createCell(i);
                cell.setCellValue(tableModel.getColumnName(i));
            }
    }

    private void poblarExcel(Sheet sheet, TableModel tableModel) {
        Row row;
        Cell cell;
        for (int i = 1; i < tableModel.getRowCount()+1; i++) {
                row = sheet.createRow(i);
                for (int j = 0; j <  tableModel.getColumnCount(); j++) {
                    cell =  row.createCell(j);
                    String dinero = (j>1)? "$":"";
                    cell.setCellValue(dinero + (String)tableModel.getValueAt(i-1, j));
                }
            } 
    }

}
